export const SET_OS = 'APP/SET_OS';
export const SET_HEIGHT = 'APP/SET_HEIGHT';
export const HIDE_LOADER = 'APP/HIDE_LOADER';
export const SHOW_LOADER = 'APP/SHOW_LOADER';
export const IS_CART = 'APP/IS_CART';

export const FETCH_CATALOG = 'CATALOG/FETCH_CATALOG';
export const FETCH_CATEGORY = 'CATALOG/FETCH_CATEGORY';

export const SET_MATRIX = 'WEBXR/SET_MATRIX';
export const PLANE_DETECTED = 'WEBXR/PLANE_DETECTED';
export const RETICLE_HIT = 'WEBXR/RETICLE_HIT';
